
FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY etudiant_add.py .

EXPOSE 5002

CMD ["python", "etudiant_add.py"]
